version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: moment-timezone
    versions:
    - 0.5.32
  - dependency-name: "@date-io/moment"
    versions:
    - 2.10.6
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python-dotenv
    versions:
    - 0.15.0
    - 0.16.0
  - dependency-name: ipdb
    versions:
    - 0.13.4
    - 0.13.5
    - 0.13.6
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: coveralls
    versions:
    - 3.0.0
  - dependency-name: pytz
    versions:
    - "2020.5"
