language: python

sudo: true

python:
  - "3.7"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.cache/node_modules
    - $HOME/.cache/venvs

env:
  - DJANGO_SETTINGS_MODULE=server.test_settings
  - DATABASE_TYPE=sqlite3

before_install:
  - sudo service postgresql stop
  - sed -e 's/^port.*/port = 5433/' /etc/postgresql/10/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/10/main
  - sudo service postgresql start 10

install:
  - pipenv install --dev
  - pip install --upgrade requests
  - npm install

script:
  - python manage.py makemigrations --settings=server.test_settings
  - python manage.py migrate --settings=server.test_settings
  - coverage run manage.py test --settings=server.test_settings -v 2 
  - npm test

after_success:
- coveralls