language: python

sudo: false

python:
  - "3.7"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.cache/node_modules
    - $HOME/.cache/venvs

env:
  - DJANGO_SETTINGS_MODULE="server.test_settings"

install:
  - pipenv install --dev
  - pip install --upgrade requests
  - npm install

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run manage.py test --settings=server.test_settings -v 2 

  # - npm test

after_success:
- coveralls